# Generated by Django 6.0.1 on 2026-01-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
